# Generated by Django 3.2.9 on 2021-11-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('anime_id', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('weight', models.CharField(default='', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserSaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('previous_search', models.CharField(max_length=255)),
            ],
        ),
    ]
